#!/usr/bin/env python3
"""
Sarasota Flooring Company — Master Data Module
Single source of truth: business identity, service area, services, pricing,
neighborhoods, FAQs, checklist, reviews, blog topics.

Edit ONLY this file when you want to change a fact, price, or city. Then run
the build scripts and everything propagates across ~120 pages.
"""

# ============================================================================
# BUSINESS IDENTITY
# ============================================================================
BUSINESS = {
    "name": "Sarasota Flooring Company",
    "short_name": "Sarasota Flooring Co.",
    "legal_name": "Sarasota Flooring Company LLC",
    "domain": "sarasotaflooringcompany.com",
    "phone": "+19412413724",
    "phone_display": "(941) 241-3724",
    "phone_tel": "+19412413724",
    "email": "hello@sarasotaflooringcompany.com",
    "street": "8125 Lakewood Main Street, Suite 207",   # virtual office in Lakewood Ranch (34212)
    "city": "Lakewood Ranch",
    "city_slug": "lakewood-ranch",
    "state": "FL",
    "state_long": "Florida",
    "zip": "34212",
    "country": "US",
    "lat": "27.4181",
    "lng": "-82.3884",
    "year_founded": 2024,
    "rating": "5.0",
    "review_count": 12,
    "tagline": "Owner-installed. Owner-guaranteed.",
    "tagline_long": "Sarasota and Manatee County's owner-supervised flooring installer — every job hand-overseen, never subbed out.",
    "unique_stat_number": "100%",
    "unique_stat_full": "100% of installs hand-supervised by the owner — no subcontracted crews, no exceptions",
    "checklist_name": "Sarasota Flooring Co. 63-Point Installation Standard",
    "checklist_points": 63,
    "guarantee": "Two-year written workmanship guarantee on every install — the longest in the Sarasota market.",
    "response_time": "Free in-home estimate within 24 hours, often same-day across Sarasota & Manatee.",
    "google_profile": "https://g.page/sarasota-flooring-co",
    "google_review_url": "https://g.page/r/sarasota-flooring-co/review",
    "facebook": "",
    "instagram": "",
    "yelp": "",
    "thumbtack": "",
    "angi": "",
    "houzz": "",
    "bbb": "",
    "license": "Manatee County Local Business Tax Receipt",
    "hours": [
        ("Monday","07:00","19:00"),
        ("Tuesday","07:00","19:00"),
        ("Wednesday","07:00","19:00"),
        ("Thursday","07:00","19:00"),
        ("Friday","07:00","19:00"),
        ("Saturday","08:00","17:00"),
        ("Sunday","09:00","16:00"),
    ],
    # Sister/partner sites for backlink network (Luciano's portfolio)
    "partner_sites": [
        ("Braza Cleaning Services", "https://brazacleaning.com", "Central Florida cleaning specialists"),
        ("Ocoee Concrete", "https://ocoeeconcrete.com", "Central Florida concrete & pavers"),
        ("The Villages Remodeling", "https://thevillagesremodeling.com", "Premier remodeling in The Villages"),
    ],
}

# Quick helpers
WA_LINK = f"https://wa.me/{BUSINESS['phone'].lstrip('+')}?text=Hi%20Sarasota%20Flooring%20Company%2C%20I%27d%20like%20a%20free%20estimate."
SMS_LINK = f"sms:{BUSINESS['phone']}?body=Hi%20Sarasota%20Flooring%20Company%2C%20I%27d%20like%20a%20free%20estimate."
TEL_LINK = f"tel:{BUSINESS['phone']}"

# ============================================================================
# SERVICE AREA — 8 cities across Sarasota & Manatee Counties
# All neighborhoods, ZIPs, landmarks are REAL and verified.
# ============================================================================
CITIES = {
    "sarasota": {
        "name": "Sarasota",
        "slug": "sarasota",
        "county": "Sarasota County",
        "state": "FL",
        "zips": ["34231","34232","34233","34234","34235","34236","34237","34238","34239","34240","34241","34242","34243"],
        "population": "57,000+ city · 460,000+ Sarasota County",
        "growth": "11% county growth 2020–2025 (US Census)",
        "lat": "27.3364",
        "lng": "-82.5307",
        "neighborhoods": [
            "Downtown Sarasota","Laurel Park","Southside Village","Indian Beach / Sapphire Shores","Cherokee Park",
            "Granada","Hudson Bayou","McClellan Park","Arlington Park","Bay Point Park",
            "Bird Key","Lido Key","St. Armands Key","Palmer Ranch","Gulf Gate",
            "Bay Hills","Forest Lakes","Pinecraft","The Meadows","Three Oaks",
        ],
        "context": "Sarasota proper runs from the historic bayfront grid downtown out to Palmer Ranch and Gulf Gate in the south — a thirteen-ZIP city that's equal parts working-class craftsman bungalows and seven-figure waterfront estates. Our flooring calls cluster in three places: the 1920s and 1950s homes around Laurel Park and Southside Village that need original heart-pine refinished or replaced; the master-planned communities along Palmer Ranch where builder-grade carpet is hitting fifteen years old; and the keys (Bird, Lido, St. Armands) where saltwater air, hurricane recovery, and high-end finishes intersect in ways most installers aren't equipped to handle.",
        "context_short": "Sarasota — the cultural and economic anchor of the region. 57,000 inside city limits, 460,000+ in the county. Mix of historic bungalows, mid-century ranches, gated golf communities, and barrier-island estates.",
        "humidity_note": "Sarasota's inside-the-bay microclimate runs five to eight percent higher humidity than Lakewood Ranch in summer — which is why we extend hardwood acclimation from 72 to 96 hours on Bird Key, Lido, and St. Armands installs.",
        "landmarks": "St. Armands Circle, the John Ringling Bridge, Sarasota Bayfront Park, Selby Botanical Gardens, the Van Wezel, Ed Smith Stadium",
        "primary_market": "Mix of historic downtown homes, mid-century renovations, gated golf-course communities, and waterfront luxury",
        "trade_class": "Sarasota County Building Department",
    },
    "bradenton": {
        "name": "Bradenton",
        "slug": "bradenton",
        "county": "Manatee County",
        "state": "FL",
        "zips": ["34201","34202","34203","34205","34207","34208","34209","34210","34211","34212"],
        "population": "60,000+ city · 425,000+ Manatee County",
        "growth": "13% population growth 2020–2025",
        "lat": "27.4989",
        "lng": "-82.5748",
        "neighborhoods": [
            "Heritage Harbour","River Strand","Mill Creek","Tara Preserve","Stoneybrook at Heritage Harbour",
            "Country Club East","River Wilderness","Rosedale Golf & Country Club","Esplanade Golf","Watercolor Place",
            "Palma Sola","West Bradenton","Cortez","Perico Island","Harbour Isle",
            "Braden Woods","University Park","River Place","Greyhawk Landing","Waterlefe",
        ],
        "context": "Bradenton is Manatee County's seat — a working river town at the mouth of the Manatee River that's added more than seven thousand residents since 2020. The east half (where our 34212 home base sits) is dominated by gated golf communities like Heritage Harbour, River Strand, and Greyhawk Landing; the west half holds 1960s and 1970s block ranches along Palma Sola and Cortez that buyers are gut-renovating month after month. The combination is gold for flooring: brand-new communities aging into their first carpet replacements, and old houses getting their terrazzo and parquet ripped up for the first time in fifty years.",
        "context_short": "Bradenton — Manatee County seat. 60,000 inside city limits, 425,000+ in the metro. Mix of east-side gated golf communities and west-side mid-century ranch renovations.",
        "humidity_note": "Bradenton dew points hold between 65 and 75°F May through October — which is why every hardwood and engineered plank gets logged through 72-hour minimum acclimation on-site before a single nail goes in.",
        "landmarks": "LECOM Park, IMG Academy, the Riverwalk, Robinson Preserve, the De Soto National Memorial, the Village of the Arts",
        "primary_market": "Gated golf-community new construction + mid-century ranch full-renovations",
        "trade_class": "Manatee County Building & Development Services",
    },
    "lakewood-ranch": {
        "name": "Lakewood Ranch",
        "slug": "lakewood-ranch",
        "county": "Manatee & Sarasota Counties",
        "state": "FL",
        "zips": ["34202","34211","34212","34240","34238"],
        "population": "65,000+ residents across 35+ villages",
        "growth": "#1 best-selling master-planned community in the US — eight years running (RCLCO Real Estate Advisors)",
        "lat": "27.4181",
        "lng": "-82.3884",
        "neighborhoods": [
            "Country Club East","The Lake Club","Esplanade Golf & Country Club","Polo Run","Lorraine Lakes",
            "Indigo","Solera","Azario","Cresswind","Sapphire Point",
            "Mallory Park","Park East","Star Farms","Avaunce","Arbor Grande",
            "Edgewater","Greenbrook","Summerfield","Hillside","Hawthorn Park",
        ],
        "context": "Lakewood Ranch is the largest master-planned community in the United States by sales volume — more than thirty-five villages spread across thirty-three thousand acres straddling the Manatee-Sarasota county line. Our home base in the 34212 ZIP puts us inside the community itself. The flooring profile here is unique: ninety-five percent of homes are post-2005 construction, almost all on slab, almost all with builder-grade engineered hardwood or porcelain tile that's now reaching its fifteen-to-twenty-year replacement window. The Lake Club and Country Club East lean toward wide-plank European white oak; the family villages (Mallory Park, Park East, Lorraine Lakes) move heavy in SPC luxury vinyl plank.",
        "context_short": "Lakewood Ranch — the United States' best-selling master-planned community for eight straight years. 65,000+ residents across 35+ villages. Slab-on-grade construction dominates; engineered hardwood and SPC luxury vinyl are the volume products.",
        "humidity_note": "Lakewood Ranch's planned-community HVAC standards run tighter than older Bradenton neighborhoods — interior humidity typically holds at 45–55%, which lets us install wider-plank hardwood (up to 10″) with confidence that other parts of the county can't support.",
        "landmarks": "Main Street at Lakewood Ranch, Waterside Place, Premier Sports Campus, Nathan Benderson Park, the Mall at University Town Center, Sarasota Polo Club",
        "primary_market": "Post-2005 builder homes in gated villages — engineered hardwood and premium SPC vinyl dominate",
        "trade_class": "Split — Manatee County north of SR-70, Sarasota County south",
    },
    "venice": {
        "name": "Venice",
        "slug": "venice",
        "county": "Sarasota County",
        "state": "FL",
        "zips": ["34285","34292","34293","34275"],
        "population": "26,000+ city · 90,000+ greater Venice",
        "growth": "16% population growth 2020–2025 — fastest-growing zone in Sarasota County",
        "lat": "27.0998",
        "lng": "-82.4543",
        "neighborhoods": [
            "Island of Venice","Venice Gardens","South Venice","Venice East","Venezia Park",
            "Pelican Pointe","Venetian Golf & River Club","Renaissance","Wellen Park","Sarasota National",
            "IslandWalk","Gran Paradiso","Stoneybrook at Venice","Toscana Isles","Grand Palm",
            "Plantation Golf","Capri Isles","Waterford","Bay Indies","Wellington Chase",
        ],
        "context": "Venice is the fastest-growing city in Sarasota County — Wellen Park alone has added more than ten thousand homes since 2019, and the school-district expansion that goes with it has pulled a wave of young families into the 34293 ZIP. The flooring market splits in three: the historic island of Venice (1920s Mediterranean-revival homes with original terrazzo and Cuban-tile floors that owners either restore or replace); the Wellen Park / IslandWalk new-build cluster (slab construction, builder packages, lots of LVP and tile upgrades during the first-owner window); and the established golf communities (Pelican Pointe, Venetian Golf) where 2000s engineered hardwood is hitting its replacement year.",
        "context_short": "Venice — Sarasota County's fastest-growing city. 26,000 in city limits, 90,000+ greater Venice. Wellen Park is the dominant new-construction market; Island of Venice holds historic Mediterranean-revival homes with restorable original floors.",
        "humidity_note": "Venice's Gulf-front exposure puts salt-air corrosion into the moisture equation — we use marine-grade fasteners and stainless transition strips standard on every install west of US-41.",
        "landmarks": "Venice Beach, Sharky's on the Pier, the Venice Jetty, Wellen Park downtown, Cool Today Park (Atlanta Braves spring training), Historic Downtown Venice",
        "primary_market": "Wellen Park new-build first-owner upgrades + historic island restoration",
        "trade_class": "Sarasota County Building Department, Venice satellite office",
    },
    "parrish": {
        "name": "Parrish",
        "slug": "parrish",
        "county": "Manatee County",
        "state": "FL",
        "zips": ["34219"],
        "population": "12,000+ — projected to triple by 2030",
        "growth": "One of the five fastest-growing ZIP codes in Florida (US Census 2024)",
        "lat": "27.5872",
        "lng": "-82.4290",
        "neighborhoods": [
            "Crosscreek","Canoe Creek","Aviary at Rutland Ranch","North River Ranch","Twin Rivers",
            "Forest Creek","Silverleaf","Ancient Oaks","River Wilderness","Foxbrook",
            "Salt Meadows","Isles at BayView","Avanti at Waterside","Copperstone","Bella Lago",
        ],
        "context": "Parrish is the explosive-growth corner of north Manatee County — a town that had three thousand residents in 2010, has twelve thousand today, and is on track for more than thirty-five thousand by 2030 as North River Ranch, Crosscreek, Canoe Creek, and a half-dozen other DR Horton, Lennar, and Neal-built communities fill in along the 301 and Moccasin Wallow corridor. Nearly every home is new construction on slab. The flooring opportunity here is volume work in the first-owner upgrade window — almost every closing buyer wants to ditch the standard carpet in primary bedrooms within ninety days of move-in, and the standard tile in the wet areas often gets replaced or expanded as well.",
        "context_short": "Parrish — north Manatee County's growth engine. 12,000 residents today, on track for 35,000+ by 2030. Almost entirely new-construction slab homes — high volume of first-owner upgrade work.",
        "humidity_note": "Parrish sits twenty minutes inland — dew points run two to four percent lower than coastal Bradenton and Anna Maria, which slightly widens our installable product range in summer.",
        "landmarks": "Parrish Civic Center, Florida Railroad Museum, the Parrish Heritage Loop, North River Ranch amenity center",
        "primary_market": "New-construction first-owner flooring upgrades — LVP, tile, hardwood swap-ins on builder packages",
        "trade_class": "Manatee County Building & Development Services",
    },
    "palmetto": {
        "name": "Palmetto",
        "slug": "palmetto",
        "county": "Manatee County",
        "state": "FL",
        "zips": ["34221"],
        "population": "14,000+ city · 35,000+ greater Palmetto",
        "growth": "8% population growth 2020–2025",
        "lat": "27.5214",
        "lng": "-82.5723",
        "neighborhoods": [
            "Riviera Dunes","Snead Island","Terra Ceia","Artisan Lakes","Esplanade at Artisan Lakes",
            "Lakeside Preserve","Palmetto Estates","Bayou Estates","Trevesta","Sanctuary Cove",
            "Heron Creek","The Pointe at Riviera Dunes","Sugar Mill Lakes","Foxbrook","Buffalo Creek",
        ],
        "context": "Palmetto sits directly across the Manatee River from Bradenton — historically a working-class fishing-village town that's now absorbing the spillover from north-Bradenton growth. The flooring market here is bimodal: high-end waterfront work in Riviera Dunes and Snead Island (the most expensive ZIP in west Manatee), and value-grade renovation work in the older Palmetto Estates and downtown grids where 1950s and 1960s block homes are turning over to first-time buyers and investors. We do a meaningful amount of vacation-rental work on Snead Island and at the marinas — LVP, tile, and stair-tread upgrades sized for short-term-rental wear.",
        "context_short": "Palmetto — Manatee County's river town. 14,000 inside city limits, 35,000+ greater Palmetto. Bimodal flooring market: Riviera Dunes and Snead Island waterfront premium work plus value-grade renovation in the older grids.",
        "humidity_note": "Snead Island and Terra Ceia sit at the mouth of the Manatee — salt-air exposure rivals Anna Maria, so we use the same marine-grade fastener and stainless-trim spec on every install west of US-41.",
        "landmarks": "Emerson Point Preserve, the Manatee River Bridge, Regatta Pointe Marina, Sutton Park, the Palmetto Historic District",
        "primary_market": "Waterfront premium installs at Riviera Dunes/Snead Island + value-grade renovation in the older downtown grids",
        "trade_class": "Manatee County Building & Development Services",
    },
    "siesta-key": {
        "name": "Siesta Key",
        "slug": "siesta-key",
        "county": "Sarasota County",
        "state": "FL",
        "zips": ["34242"],
        "population": "5,500+ year-round · 25,000+ peak season",
        "growth": "Tourism revenue up 22% 2020–2024 — drives short-term rental flooring demand",
        "lat": "27.2659",
        "lng": "-82.5410",
        "neighborhoods": [
            "Siesta Village","Crescent Beach","Turtle Beach","Point of Rocks","Sanderling Club",
            "Beach Road","Higel Avenue corridor","Midnight Cove","Excelsior Beach to Bay","Beach Place",
            "Tropical Sands","Casa del Mar","Crystal Sands","Sea Manor","Sara Sands",
        ],
        "context": "Siesta Key is an eight-mile barrier island with two distinct flooring markets stacked on top of each other. The full-time residential market — Sanderling Club, Higel Avenue, the bayside estates — runs premium: wide-plank European white oak, large-format porcelain, real terrazzo restoration. The short-term-rental market — and Siesta Key has one of the densest concentrations of legally permitted STRs in Florida — needs flooring that survives one hundred fifty turnovers a year, salt air, sand abrasion, and the constant moisture cycle of beach renters. We install SPC luxury vinyl plank, marine-grade tile, and reinforced stair treads on the STR side; the residential side gets the premium treatment with full acclimation protocols.",
        "context_short": "Siesta Key — Sarasota County's premier barrier island. 5,500 year-round residents, 25,000+ during peak season. Bimodal market: ultra-premium residential plus one of Florida's densest legal short-term rental clusters.",
        "humidity_note": "Salt-air corrosion on Siesta is severe — within a quarter mile of the Gulf we spec stainless transitions, marine-grade fasteners, and adhesive systems rated for chloride exposure on every install.",
        "landmarks": "Siesta Beach (ranked #1 in the US three times), Siesta Village, the Big Pass, Point of Rocks, Crescent Beach, Turtle Beach",
        "primary_market": "STR (short-term-rental) reflooring at scale + premium full-time residential",
        "trade_class": "Sarasota County Building Department + Siesta Key Improvement District",
    },
    "longboat-key": {
        "name": "Longboat Key",
        "slug": "longboat-key",
        "county": "Sarasota & Manatee Counties",
        "state": "FL",
        "zips": ["34228"],
        "population": "7,000+ year-round · 20,000+ peak season",
        "growth": "Highest median home value in the Sarasota–Manatee MSA ($1.8M+, 2025)",
        "lat": "27.4181",
        "lng": "-82.6512",
        "neighborhoods": [
            "Longboat Key Club","Bay Isles","Country Club Shores","Sleepy Lagoon","Sands Point",
            "Cedars East","Buttonwood Cove","Beachplace","Sea Place","L'Ambiance",
            "The Water Club","Beachside Condominiums","Conquistador","Buttonwood Harbor","Privateer",
        ],
        "context": "Longboat Key is the most expensive ZIP code in the Sarasota–Manatee region — twelve miles of barrier-island shoreline with a median home value north of one point eight million dollars. The flooring market here is almost entirely high-end residential and Mid-Rise condominium work: floor-to-ceiling porcelain, wide-plank engineered hardwood (sometimes flown-in European oak), bookmatched marble, custom inlay work in foyers. There are no commodity installs on Longboat. Every job we do here gets full white-glove protocol — protected interior pathways, daily clean-down, end-of-day walkthroughs with the homeowner. The mid-rise condo work is its own discipline: HOA approval packets, freight elevator scheduling, neighbor-notification windows, and material-staging logistics that most installers don't have the patience for.",
        "context_short": "Longboat Key — the most expensive ZIP in the region. 7,000 year-round residents, 20,000+ during peak season. Median home value $1.8M+. Almost entirely high-end residential and mid-rise condominium flooring.",
        "humidity_note": "Longboat's combination of saltwater air and 24/7 air conditioning in high-rise condos creates one of the most challenging humidity gradients in the state — we extend acclimation to a full 96-hour minimum on every install above the third floor.",
        "landmarks": "Longboat Key Club, Bay Isles Beach Club, Buttonwood Harbour Marina, the Longboat Pass Bridge, St. Armands Circle (across the Ringling Bridge)",
        "primary_market": "Premium residential + mid-rise condo work — porcelain, wide-plank engineered hardwood, marble, custom inlays",
        "trade_class": "Town of Longboat Key Building Department",
    },
}

CITY_ORDER = ["sarasota","bradenton","lakewood-ranch","venice","parrish","palmetto","siesta-key","longboat-key"]

# ============================================================================
# SERVICES — 6 services, each with full content for the service-index page
# AND parameterized for the [service]/[city]/ pages.
# ============================================================================
SERVICES = {
    "hardwood-flooring": {
        "name": "Hardwood Flooring",
        "slug": "hardwood-flooring",
        "short": "Hardwood",
        "h1_phrase": "Hardwood Flooring",
        "icon": "01",
        "intro_lead": "Wide-plank European white oak, engineered American oak, solid hickory and walnut — installed by hand, acclimated for the Gulf Coast, and warranted for two years in writing.",
        "intro_long_p1": "Hardwood is still the single most resale-defensible flooring you can install in a Sarasota or Manatee County home — but the climate punishes shortcuts. The number-one mistake we get hired to repair is rushed acclimation: planks shipped from a temperature-controlled warehouse straight onto a slab that hasn't been moisture-tested, installed in a house where the HVAC has been off for a week of staging. That floor will gap, cup, or crown inside the first summer. Every Sarasota Flooring Company install logs a seventy-two-hour minimum on-site acclimation with a digital hygrometer, and we extend to ninety-six hours on Siesta Key, Longboat Key, and any install west of US-41 where salt-air humidity gradients hit hardest.",
        "intro_long_p2": "We work in two categories. <strong>Solid hardwood</strong> is three-quarter-inch tongue-and-groove, nail-down on plywood subfloors, and sandable up to eight times in its lifetime — still our pick for second-story renovations and the historic homes around Laurel Park and the Island of Venice. <strong>Engineered hardwood</strong> is the right answer for ninety percent of slab-on-grade homes in Sarasota and Manatee — multi-ply construction with a real-wood top veneer, dimensionally stable enough to install over concrete with the right adhesive system. Species we stock and source weekly: European White Oak (our most-installed product), American White Oak, Red Oak, Hickory, Walnut, Maple, Brazilian Cherry, and Acacia. Widths from three inches up to ten; flat, hand-scraped, and wire-brushed surface textures.",
        "scope_items": [
            "Solid hardwood installation (3/4″ tongue-and-groove, nail-down on plywood)",
            "Engineered hardwood installation (5″–9″ widths, glue-down or floating)",
            "Wide-plank European White Oak (7″–10″) — our most-installed premium product",
            "Custom herringbone &amp; chevron laydowns",
            "Nail-down installation on plywood subfloors",
            "Glue-down installation on concrete slabs with full moisture testing",
            "Floating engineered installation with click-lock systems",
            "Subfloor moisture testing — calcium chloride + pin meter, both logged",
            "Self-leveling concrete pours for slab dips up to 1.5 inches",
            "Vapor-retarder installation on suspect concrete slabs",
            "Threshold &amp; transition strip carpentry",
            "Quarter-round and shoe-mold matching",
            "Flush-mount baseboard refits where requested",
            "Stair tread &amp; nosing integration with the field floor",
            "Toilet pull-and-reset, appliance moves, debris haul-away",
            "Optional sand-and-refinish of existing hardwood (water-based or oil-based)",
        ],
        "pricing_rows": [
            ("Engineered Hardwood (5″ wide)", "$9–$12 / sq ft installed", "Glue-down or nail-down"),
            ("Engineered Hardwood (7–9″ wide)", "$11–$15 / sq ft installed", "Most-installed in Lakewood Ranch & The Lake Club"),
            ("Solid Hardwood (3/4″, 3–5″ wide)", "$10–$14 / sq ft installed", "Nail-down on plywood subfloor only"),
            ("Premium European White Oak (wide plank)", "$14–$19 / sq ft installed", "Character-grade, 7–10″ width"),
            ("Custom Herringbone Laydown", "$16–$24 / sq ft installed", "Labor roughly doubles vs. straight plank"),
            ("Custom Chevron Laydown", "$18–$26 / sq ft installed", "Our most-premium hardwood install"),
            ("Subfloor Self-Leveling (per room)", "$250–$700", "When pin-meter shows 1/4″+ dip in 10 ft"),
            ("Old Flooring Removal &amp; Haul", "$1.75–$3.25 / sq ft", "Carpet, laminate, or tile demo"),
            ("Sand &amp; Refinish Existing Hardwood", "$4.50–$7 / sq ft", "Three-coat water-based or oil-based"),
        ],
        "faqs": [
            ("Can I install solid hardwood on a Florida slab?",
             "We don't recommend it. The combination of slab moisture and Gulf-Coast humidity makes solid hardwood prone to cupping, gapping, and crowning when glued or nailed directly onto concrete. Engineered hardwood — with a multi-ply core that resists dimensional movement — is the correct call for ninety-five percent of slab-on-grade homes in Sarasota and Manatee. The exceptions are homes where we can install a 5/8″ plywood underlayment over the slab first; that raises the finished floor height by an inch, which affects door clearance, transitions, and baseboard returns, so we walk you through the tradeoffs before the work starts."),
            ("How long does hardwood acclimate on-site?",
             "Seventy-two hours is our floor across most of Sarasota and Manatee. We extend to ninety-six hours on barrier-island work (Siesta Key, Longboat Key, Anna Maria) and on any home where the HVAC has been off for staging or storm-prep. Boxes get opened on the jobsite, planks cross-stacked so air circulates around every face, and a digital hygrometer logs jobsite humidity for the full window. The acclimation log goes into your final job folder."),
            ("Engineered vs. solid — what's actually different?",
             "Solid hardwood is one piece of wood, three-quarters of an inch thick. It can be sanded and refinished up to eight times across its lifetime, which is why it remains the standard for premium plywood-subfloor installs and historic restorations. Engineered hardwood is a real-wood top veneer (typically two to six millimeters) bonded to a multi-ply substrate; it's far more dimensionally stable, installs below grade, and can usually be refinished one or two times. For Florida slab homes we recommend engineered nine times out of ten."),
            ("How long does the whole install take?",
             "A typical 1,200–1,800 sq ft hardwood install runs three to five working days from demo to final walkthrough. Day one is demolition and subfloor prep; day two is finishing acclimation and starting the laydown; days three and four are the bulk of installation plus transitions; day five is quarter-round, baseboard return, and the homeowner walkthrough. Herringbone and chevron jobs run six to ten days. Stair treads add one full day."),
        ],
    },
    "vinyl-plank-flooring": {
        "name": "Luxury Vinyl Plank (LVP) Flooring",
        "slug": "vinyl-plank-flooring",
        "short": "Vinyl Plank",
        "h1_phrase": "Vinyl Plank Flooring",
        "icon": "02",
        "intro_lead": "Fully waterproof. Scratch-resistant. Dimensionally stable in Florida humidity. The smartest dollar-per-square-foot floor you can put in a Sarasota kitchen, family room, or short-term rental.",
        "intro_long_p1": "Luxury vinyl plank (LVP) and stone-plastic composite (SPC) became the dominant new-floor category across Sarasota and Manatee for four practical reasons stacked together: they're one hundred percent waterproof, they shrug off dog claws and dropped pans, they cost a fraction of real hardwood per square foot, and the visual gap between a premium SPC plank and an actual oak floor has gotten genuinely small from six feet away. We install <strong>click-lock floating systems</strong> (faster install, no glue, individual planks replaceable down the road) and <strong>full glue-down systems</strong> (more permanent, zero flex underfoot, the right answer for open-plan rooms above 800 square feet and for commercial-grade installations).",
        "intro_long_p2": "Where we earn our keep is the short-term-rental segment. Siesta Key, Longboat Key, Anna Maria Island, and the Wellen Park rental cluster see five times the foot traffic of a primary residence, get cleaned with chemicals most homeowners would never touch, and need to read brand-new in listing photos for the next decade. For most Sarasota–Manatee residential clients we land on a click-lock SPC plank at 6.5 mm with a 22-mil wear layer — that's the sweet spot for durability, price, and visual quality. For STR work and commercial we step up to 8 mm with a 28-mil wear layer and glue down.",
        "scope_items": [
            "Click-lock LVP installation (floating, no adhesive)",
            "Full glue-down LVP installation for large open-plan and commercial spaces",
            "SPC (Stone-Plastic Composite) plank installation",
            "WPC (Wood-Plastic Composite) plank installation",
            "Cork or foam underlayment when the manufacturer specs it",
            "Calcium-chloride moisture testing on slabs before glue-down",
            "Concrete slab self-leveling for dips, low spots, and cracks",
            "Old flooring removal &amp; haul-away (carpet, tile, sheet vinyl)",
            "Transition strip and reducer installation, color-matched",
            "Flush-mount transitions to tile or carpet",
            "Custom LVP stair treads with matching nosings",
            "Quarter-round and shoe-mold installation",
            "Toilet pull-and-reset, appliance moves",
            "Vapor barrier installation on suspect slabs",
        ],
        "pricing_rows": [
            ("Standard LVP (4 mm, 12-mil wear)", "$1.75–$3.25 / sq ft installed", "Builder-grade, rental-friendly"),
            ("Mid-Range LVP / SPC (6 mm, 20-mil)", "$2.75–$5.50 / sq ft installed", "Most-installed for primary residences"),
            ("Premium SPC (8 mm, 22+ mil wear)", "$4.25–$7.50 / sq ft installed", "Pet-proof, lifetime residential warranty"),
            ("Wide-Plank Luxury LVP (9″+)", "$5.50–$9.50 / sq ft installed", "Hardwood-mimicking, premium-tier visual"),
            ("Glue-Down Commercial LVP", "$3.25–$6.50 / sq ft installed", "STRs, AirBnBs, high-traffic"),
            ("LVP Stair Treads (per tread)", "$65–$105 each", "Includes nosing and matching riser"),
            ("Slab Self-Leveling (per room)", "$250–$700", "When dip exceeds 3/16″ across 10 ft"),
            ("Old Flooring Removal &amp; Haul", "$1.75–$3.25 / sq ft", "Carpet/tile/sheet-vinyl demo"),
        ],
        "faqs": [
            ("Is luxury vinyl plank really waterproof?",
             "Yes — fully through the core. Modern LVP and SPC planks are submersible: you can leave a plank in water for days and it will not swell, warp, or delaminate. The seams between planks are tight enough that surface water (a dishwasher leak, a pet accident, an AC-condensate overflow) won't reach the subfloor for hours. The caveat: waterproof flooring doesn't make a waterproof house. Standing water against a baseboard for days will still get into the wall cavity behind the floor — the plank itself won't fail, but the assembly around it can."),
            ("Click-lock vs. glue-down — which is right for me?",
             "Click-lock (floating) is faster to install, easier to repair (you can pop up a damaged plank and swap it), and gentler on subfloors with minor imperfections. Glue-down is more permanent, has zero flex underfoot (feels closer to tile or hardwood), and is the right answer for open-plan spaces above 800 sq ft, commercial buildings, and rooms with heavy furniture like pool tables or commercial appliances. For most Sarasota–Manatee residential work we click-lock. For short-term rentals and commercial we glue down."),
            ("Will the LVP look fake?",
             "Depends entirely on what you buy. Builder-grade LVP at $1.75/sq ft has visible pattern repeats — you'll see the same knot or grain reappear every four to six planks, and the embossing doesn't always align with the printed grain. Mid-tier and premium SPC at $4 and above has dozens of unique plank visuals, deeper embossing, matte finishes, and beveled edges that read remarkably close to real hardwood from anywhere outside ten feet. We bring physical samples to your home and show you the cost-vs-realism tradeoff in person before you commit."),
            ("How long does an LVP install take?",
             "A typical 1,000–1,500 sq ft floating LVP install runs two to three working days: day one is demolition and subfloor prep, day two is installation, day three is transitions and trim. Glue-down jobs add one to two days for adhesive cure time. Stair treads add one day. Any subfloor self-leveling adds twenty-four hours of dry time before installation can begin."),
        ],
    },
    "tile-installation": {
        "name": "Tile Installation",
        "slug": "tile-installation",
        "short": "Tile",
        "h1_phrase": "Tile Installation",
        "icon": "03",
        "intro_lead": "Porcelain, ceramic, natural stone, and large-format slab — set flat, set straight, set to the slope your shower pan actually needs. TCNA-spec substrate prep on every install.",
        "intro_long_p1": "Tile is the most installation-sensitive flooring product on the market. The tile itself is inert and durable; the failure points are always underneath — improperly prepared substrates, the wrong setting mortar, missing crack-isolation membranes, skipped lippage controls. We install everything from 4-inch ceramic field tile to 24x48 large-format porcelain to 48x48 marble-look slabs, and the larger the format, the more critical the prep becomes. A 24x48 porcelain on a slab with a one-eighth-inch dip will sit visibly cupped in the finished room. The same dip is invisible under 12-inch tile.",
        "intro_long_p2": "We follow the TCNA (Tile Council of North America) handbook for substrate prep, setting mortars, and crack-isolation membranes — that's the published spec for tile that doesn't crack when the slab below it does. For wet areas (showers, primary baths, splash zones) we install Schluter Kerdi or Wedi waterproofing systems before a single tile gets set. The vast majority of our tile-failure repair calls in Sarasota trace back to the original installer skipping either substrate prep or waterproofing. Once tile is set wrong, the only real fix is to take it back out — which is why we do the prep right the first time.",
        "scope_items": [
            "Ceramic field tile (4″–18″ formats)",
            "Porcelain field tile (12″–24″ formats)",
            "Large-format porcelain (24x48, 30x60, 48x48 slabs)",
            "Natural stone — marble, travertine, limestone, slate",
            "Wood-look porcelain plank tile",
            "Hexagon, herringbone, and chevron field patterns",
            "Schluter Kerdi shower waterproofing systems",
            "Wedi waterproof shower-pan systems",
            "Crack-isolation membrane on slab installations (Ditra, NobleSeal)",
            "Custom shower-niche framing and tile lining",
            "Linear drain installation with proper slope-to-drain",
            "Curbless walk-in shower-pan construction",
            "Backsplash and accent-wall tile",
            "Penetrating sealer application on porous stone",
            "Mortar-bed shower-pan construction (when spec requires)",
            "Lippage control with leveling clip systems on large-format work",
        ],
        "pricing_rows": [
            ("Standard Ceramic / Porcelain Field Tile (12″–18″)", "$6–$10 / sq ft installed", "Most-installed format"),
            ("Large-Format Porcelain (24″+)", "$9–$15 / sq ft installed", "Requires lippage control"),
            ("Wood-Look Porcelain Plank", "$8–$13 / sq ft installed", "Premium visual at tile durability"),
            ("Natural Stone — Marble / Travertine", "$12–$22 / sq ft installed", "Includes sealing"),
            ("Custom Herringbone / Chevron Layout", "$11–$18 / sq ft installed", "Labor roughly doubles vs. straight"),
            ("Schluter Kerdi Shower (full waterproofing)", "$1,800–$3,800 per shower", "Includes pan, walls, niche"),
            ("Linear-Drain Curbless Shower", "$2,800–$5,200 per shower", "Premium walk-in spec"),
            ("Tile Backsplash (8–25 sq ft)", "$22–$45 / sq ft installed", "Per-square-foot premium on small areas"),
            ("Old Tile Removal &amp; Haul", "$2.50–$4.50 / sq ft", "Including thinset chip-out"),
        ],
        "faqs": [
            ("Why is large-format tile so much harder to install?",
             "Large-format tile (anything 24 inches or larger on the long side) is unforgiving of substrate imperfections. A one-eighth-inch dip across ten feet is invisible under twelve-inch tile but reads as a visibly cupped corner on a 24x48. We use leveling-clip lippage systems on every large-format install, and we self-level any slab dip over three-sixteenths of an inch in ten feet before setting a single tile. The cost goes up; the failure rate goes to zero."),
            ("Do you use Schluter or a mortar-bed shower pan?",
             "We use Schluter Kerdi or Wedi waterproofing on every shower we build — they're the published spec for a watertight pan that won't fail. Mortar-bed shower pans (the old-school method with hot mop and pre-slope) still work if executed perfectly, but they have ten times the failure modes of a Schluter system and they take three times as long to install. We default to Schluter unless you specifically request mortar-bed for a historic restoration."),
            ("Can I tile over an existing tile floor?",
             "Sometimes, with conditions. The existing tile has to be tightly bonded to the substrate (no hollow spots), the surface has to be roughed up to give the new thinset a mechanical bond, and the finished floor height has to clear doors, transitions, and appliance kicks. We test the existing tile with a tap-test and an adhesion-pull before quoting. If less than five percent of the existing tile is hollow we'll set over the top; above that, we'll quote the full removal."),
            ("How long does a tile install take?",
             "Field tile installation runs roughly one day per 200–300 square feet of installation area, plus a day for setting cure and a day for grouting and sealing. A typical 600 sq ft kitchen-and-living-room tile install runs three to four working days. Shower waterproofing and tile work add three to five days per shower depending on complexity. Large-format and natural stone add cure time."),
        ],
    },
    "laminate-flooring": {
        "name": "Laminate Flooring",
        "slug": "laminate-flooring",
        "short": "Laminate",
        "h1_phrase": "Laminate Flooring",
        "icon": "04",
        "intro_lead": "AC4 and AC5 commercial-grade laminate — the highest scratch resistance of any wood-look flooring at a fraction of hardwood pricing. Right answer for kids, pets, and rental properties.",
        "intro_long_p1": "Laminate has changed dramatically over the last decade. The thin, hollow-sounding laminate of the 1990s has been replaced by 12 mm AC4 and AC5 commercial-rated products with deep embossed-in-register surfaces, beveled edges, and visuals that read closer to real hardwood than premium engineered. The two structural advantages laminate holds over LVP: it's significantly more scratch-resistant (AC5 is rated for heavy commercial traffic), and the surface is harder underfoot so it doesn't dent under heavy furniture legs the way some vinyl planks will.",
        "intro_long_p2": "The tradeoff: laminate is not waterproof. Modern water-resistant laminates (Pergo Outlast+, Mohawk RevWood) hold up to splashes and short spills, but they are not the right answer for primary bathrooms, laundry rooms, or any space where standing water is a real possibility. For those spaces we steer clients to LVP. For everywhere else — bedrooms, living rooms, hallways, home offices, kid playrooms — laminate is often the smartest dollar-per-square-foot install on the market.",
        "scope_items": [
            "12 mm AC4 residential laminate installation",
            "12 mm AC5 commercial-grade laminate installation",
            "Water-resistant laminate (Pergo Outlast+, RevWood, Quick-Step)",
            "Click-lock floating installation",
            "Pre-installed attached underlayment products",
            "Add-on premium underlayment (cork, foam, or moisture-barrier combo)",
            "Subfloor moisture testing on slab installs",
            "Concrete slab self-leveling where required",
            "Old flooring removal &amp; haul-away",
            "Transition strip and reducer installation",
            "Custom laminate stair treads with matching nosing",
            "Quarter-round and shoe-mold installation",
            "Toilet pull-and-reset, appliance moves",
        ],
        "pricing_rows": [
            ("Standard Laminate (8 mm, AC3)", "$2.25–$3.75 / sq ft installed", "Builder-grade residential"),
            ("Mid-Range Laminate (10–12 mm, AC4)", "$3.25–$5 / sq ft installed", "Most-installed for residences"),
            ("Premium Laminate (12 mm, AC5)", "$4.50–$6.75 / sq ft installed", "Commercial-rated, lifetime warranty"),
            ("Water-Resistant Laminate", "$4.75–$7 / sq ft installed", "For kitchens, half-baths"),
            ("Wide-Plank Premium Laminate (8″+)", "$5–$7.50 / sq ft installed", "Realistic hardwood visual"),
            ("Laminate Stair Treads", "$55–$85 per tread", "Includes nosing and matching riser"),
            ("Slab Self-Leveling (per room)", "$250–$700", "When dip exceeds 3/16″ across 10 ft"),
            ("Old Flooring Removal &amp; Haul", "$1.75–$3.25 / sq ft", "Carpet/tile/sheet-vinyl demo"),
        ],
        "faqs": [
            ("Laminate vs. LVP — which should I pick?",
             "It depends on the room. LVP is the right answer for kitchens, bathrooms, laundry rooms, and any space where standing water is a real possibility — it's fully waterproof. Laminate (especially 12 mm AC4 and AC5) is more scratch-resistant and has a harder, more authentic underfoot feel, which makes it the right answer for bedrooms, living rooms, home offices, and high-traffic dry spaces. In a typical Sarasota home we install LVP in the wet areas and laminate in the dry — best of both worlds."),
            ("Is laminate waterproof?",
             "Standard laminate is not waterproof. Water-resistant laminates (Pergo Outlast+, Mohawk RevWood, Quick-Step ImpressivePlus) will tolerate splashes and short spills, but they are not appropriate for primary bathrooms or rooms where standing water is likely. If waterproofing is the priority, we'll steer you to LVP."),
            ("Can laminate be refinished?",
             "No — laminate has a printed surface bonded to a wood-fiber core, and that surface can't be sanded or refinished. When laminate wears out (typically fifteen to twenty-five years on AC4 or AC5 in a residential install), the entire floor gets replaced. The flip side: the print layer is so durable that refinishing isn't usually required during the floor's service life."),
            ("How long does a laminate install take?",
             "Faster than most flooring types. A 1,000–1,500 sq ft floating laminate install typically runs two days: day one demo and subfloor prep, day two installation and trim. Stair treads add one day. Click-lock laminate installs faster than glue-down LVP, faster than hardwood, faster than tile."),
        ],
    },
    "stair-treads": {
        "name": "Stair Treads",
        "slug": "stair-treads",
        "short": "Stair Treads",
        "h1_phrase": "Stair Tread Replacement",
        "icon": "05",
        "intro_lead": "Engineered hardwood, solid oak, LVP, and laminate stair treads — fitted to your existing stringers, matched to your field floor, and finished in your home in two days.",
        "intro_long_p1": "Stair treads are the single most-skipped install in a flooring renovation. The field floor gets replaced; the carpeted or builder-grade pine staircase gets left alone — and then it sticks out like a sore thumb against the new hardwood or LVP downstairs. We replace stair treads in-place, matched to your new floor, with custom nosing profiles cut on-site. The work happens in your home over one to two days: tread one, riser one, then tread two and riser two, working up the staircase so the stairs remain usable for the whole job.",
        "intro_long_p2": "We install treads in every primary material — solid hardwood, engineered hardwood, LVP, laminate, tile risers, and the increasingly popular open-riser modern look. Tread fabrication happens off-site (we measure each step individually because staircases are never perfectly square) and installation happens with the entire staircase masked, dust-controlled, and walked through with the homeowner at end of day. Most full-staircase tread replacements run between fourteen and twenty-two steps; a typical home is finished start-to-finish in two days.",
        "scope_items": [
            "Solid hardwood tread fabrication (oak, hickory, walnut, maple)",
            "Engineered hardwood tread installation, matched to field floor",
            "LVP stair tread with matching nosing",
            "Laminate stair tread with matching nosing",
            "Custom nosing profile selection (bullnose, square, beveled)",
            "Riser replacement (matching painted, stained, or open-riser)",
            "Open-riser modern conversions where structurally allowed",
            "Skirt-board carpentry and refit",
            "Spindle and balustrade reinstallation where required",
            "Stain matching to existing field floor",
            "On-site refinishing of treads with three-coat finish",
            "Demo of existing carpeted treads + tack-strip removal",
            "Subfloor leveling of stringer tops where required",
            "Dust containment and end-of-day cleanup",
        ],
        "pricing_rows": [
            ("Solid Hardwood Treads (per tread, installed)", "$130–$220", "Oak, hickory, walnut, maple"),
            ("Engineered Hardwood Treads (per tread, installed)", "$110–$180", "Matched to field floor"),
            ("LVP Treads (per tread, installed)", "$65–$105", "Includes nosing"),
            ("Laminate Treads (per tread, installed)", "$55–$85", "Includes nosing"),
            ("Risers (painted or stained, per riser)", "$25–$65", "Replacement to match"),
            ("Open-Riser Modern Conversion (per stair)", "$135–$235", "Where structurally allowed"),
            ("Stain Matching &amp; On-Site Finish", "$45–$95 per tread", "Three-coat finish"),
            ("Skirt-Board Carpentry", "$35–$65 / linear ft", "When existing skirt needs refit"),
        ],
        "faqs": [
            ("Can I keep my staircase usable during the install?",
             "Yes. We replace treads in sequence — tread one and riser one go in, cure, and become walkable before tread two starts. The staircase remains usable through the entire two-day job. You'll walk on the old carpet for the half of the stairs we haven't reached yet, and on cured new treads for the half we've finished."),
            ("Do you match the treads to my new field floor?",
             "Yes. The whole point of a tread replacement during a flooring renovation is the visual continuity. We pull a sample from the field-floor production run, fabricate the treads from the same source material, and stain-match to the field floor. From the bottom of the staircase looking up, the staircase reads as part of the same install."),
            ("Can you convert closed risers to open risers?",
             "Sometimes. Open-riser conversions require us to verify that your stringer construction can hold the load without the closed-riser bracing — most modern code-built stairs can; some 1970s and earlier homes need additional stringer reinforcement first. We assess and quote per staircase."),
            ("How long does a full staircase take?",
             "A typical 14–22 step staircase replacement runs one to two working days from demo to finish, plus an overnight cure if we're doing on-site staining or finishing. Treads we pre-finish off-site go in faster — usually one day. Open-riser conversions add one day."),
        ],
    },
    "floor-repair": {
        "name": "Floor Repair",
        "slug": "floor-repair",
        "short": "Floor Repair",
        "h1_phrase": "Floor Repair",
        "icon": "06",
        "intro_lead": "Cupped hardwood. Cracked tile. Lifting LVP seams. Squeaky subfloors. Stair-tread loosening. We diagnose, scope, and repair — no full floor replacement when a targeted fix will do.",
        "intro_long_p1": "Most floor failures don't need a full replacement. A cupped hardwood plank, a cracked tile, a lifting LVP seam, a squeaky stair-tread — these are diagnosable, isolated problems. The trick is identifying the root cause before the patch, because patching the symptom over a continuing problem (moisture intrusion, subfloor movement, failed adhesive) just buys you three months before the failure comes back. We start every repair call with diagnosis — moisture testing, subfloor inspection, adhesive sampling where relevant — and then scope the targeted repair.",
        "intro_long_p2": "Repair work spans every flooring material we install: hardwood plank replacement (color-matched from stocked species), engineered hardwood seam tightening, tile pull-and-reset, grout regrouting, LVP plank swap-outs from stocked attic material, laminate replacement, and subfloor squeak elimination from above (no floor demolition required for most squeaks). Where the root cause is something we can't fix without addressing the underlying issue (water intrusion, slab cracks, joist deflection), we'll tell you up front and refer or coordinate the structural work.",
        "scope_items": [
            "Hardwood plank replacement, color-matched to existing floor",
            "Engineered hardwood seam tightening and re-glue",
            "Cupped hardwood plank diagnosis and replacement",
            "Hardwood gap-filling on legacy wide-plank installs",
            "Cracked tile pull-and-reset with grout-match",
            "Re-grout existing tile work (epoxy or sanded cement)",
            "Tile lippage correction where slab dip can be self-leveled around",
            "LVP plank swap-outs from owner-supplied attic material",
            "LVP seam re-bonding (glue-down installs)",
            "Laminate plank replacement",
            "Subfloor squeak elimination from above (no demo)",
            "Stair-tread tightening and re-fastening",
            "Moisture-source diagnosis (calcium chloride, pin meter, infrared)",
            "Carpet seam repair and re-stretching",
            "Threshold and transition strip replacement",
        ],
        "pricing_rows": [
            ("Diagnostic Visit (credited toward repair)", "$185 flat", "Moisture testing, subfloor inspection, scope report"),
            ("Hardwood Plank Replacement (per plank)", "$95–$225", "Color-matched from stocked species"),
            ("Cracked Tile Replacement (per tile)", "$95–$185", "Includes grout-match"),
            ("Tile Regrout (per sq ft)", "$3.50–$7", "Sanded cement or epoxy"),
            ("LVP Plank Swap (per plank, attic stock)", "$45–$95", "Requires homeowner-supplied matching material"),
            ("Subfloor Squeak Elimination", "$95–$185 per squeak zone", "From above, no demo"),
            ("Stair-Tread Tightening (per tread)", "$45–$95", "Re-fasten and shim"),
            ("Hourly Repair Rate", "$95 / hour, 1-hour minimum", "For undefined-scope repair work"),
        ],
        "faqs": [
            ("Can you match my old hardwood?",
             "Often, with caveats. If the existing floor is a stocked species (oak, hickory, maple, walnut) we can usually fabricate or source a matching plank and color-match the stain in-house. If the existing floor is a discontinued product or an exotic species, the match gets harder and we'll show you sample planks before we commit to the repair. For LVP and laminate we strongly recommend keeping attic stock at install time — it's the only reliable way to get an exact match years later."),
            ("Will a repair be visible?",
             "On most flooring types, no. Hardwood plank replacements with proper color-matching disappear into the field floor within a season of light exposure. Tile replacements with matched grout are essentially invisible. LVP and laminate replacements done with original-batch attic stock are invisible. Where repair work tends to show is when the original floor has aged, faded, or worn enough that fresh material reads visibly newer — that's why we do the diagnostic visit first."),
            ("How fast can you respond to a repair call?",
             "Same-week for most non-emergency calls across Sarasota and Manatee. For water-intrusion emergencies (failed dishwasher, water-heater leak, hurricane damage) we'll prioritize the call and try to get on-site within 24 hours. The diagnostic visit is $185 and credits toward any repair we end up doing."),
            ("Can you fix water damage?",
             "We can address flooring failures caused by water damage — plank replacement, seam re-bonding, subfloor drying with the right moisture-meter readings before re-install. We are not a water-mitigation company; if the water source is still active or the subfloor is saturated, we'll refer you to a licensed restoration contractor for the initial mitigation and then handle the flooring rebuild once the moisture readings are back in spec."),
        ],
    },
}

SERVICE_ORDER = ["hardwood-flooring","vinyl-plank-flooring","tile-installation","laminate-flooring","stair-treads","floor-repair"]

# ============================================================================
# 63-POINT INSTALLATION STANDARD (the proprietary checklist)
# ============================================================================
CHECKLIST = {
    "name": BUSINESS["checklist_name"],
    "points": BUSINESS["checklist_points"],
    "categories": [
        {
            "category": "Pre-Install Site Inspection",
            "icon": "📋",
            "points": [
                "Confirm site address, gate code, lockbox combination 48 hours before arrival",
                "Verify HVAC has been running at 70–74°F for minimum 7 days before delivery",
                "Walk-through with homeowner to identify any furniture moves and pet-containment needs",
                "Photograph all existing flooring, baseboards, and transitions for before-comparison",
                "Mark and protect every electrical, gas, and water shutoff in the install zone",
                "Identify all subfloor seams, expansion gaps, and existing transitions",
                "Confirm parking and dumpster placement with HOA where applicable",
                "Verify finished-floor-height clearance against all interior doors and appliance kicks",
            ],
        },
        {
            "category": "Subfloor & Moisture Diagnostics",
            "icon": "💧",
            "points": [
                "Calcium-chloride moisture test on every slab install — 24-hour reading logged",
                "Pin-meter readings at minimum 6 points per 100 sq ft for hardwood",
                "Subfloor flatness check — 1/8″ tolerance across 10 ft, self-leveled if not",
                "Visual inspection for slab cracks, hollow spots, and previous patches",
                "Pull a baseboard sample to inspect wall-to-floor moisture history",
                "Vapor-retarder spec confirmed against manufacturer requirements",
                "Subfloor squeak elimination before any new material goes down",
                "Confirm subfloor type matches selected install method (nail-down only on plywood)",
                "Existing transitions removed, evaluated, and replaced if compromised",
                "Threshold heights confirmed against new floor build-up",
            ],
        },
        {
            "category": "Material Acclimation & Inspection",
            "icon": "🌡️",
            "points": [
                "Minimum 72-hour on-site acclimation for hardwood — 96 hours on barrier islands",
                "Digital hygrometer logging through full acclimation window",
                "Open every box and cross-stack for full air circulation around every plank face",
                "Visual inspection of every plank for defects, color variation, milling errors",
                "Cull and return any defective material before installation starts",
                "Confirm batch and lot numbers match across all delivered material",
                "Verify total material count exceeds room measurement by minimum 10% waste factor",
                "Tile delivery inspected for chip, edge, and corner damage",
                "Verify mortar, grout, adhesive, and sealant lot freshness against shelf-life",
            ],
        },
        {
            "category": "Demolition & Site Protection",
            "icon": "🛡️",
            "points": [
                "Protected pathways laid from entry to install zone — no dust to other rooms",
                "Plastic sheeting on every doorway between active and inactive zones",
                "Furniture moved, padded, and protected with covers — never just shoved aside",
                "All existing flooring removed cleanly, tack strips pulled, staples flush-cut",
                "Existing baseboards removed only when specified — otherwise quarter-round added",
                "Old material loaded and hauled — site cleared end of demo day",
                "Toilets pulled and reset by us where required (no homeowner coordination)",
                "Major appliances disconnected, moved, reconnected by us",
                "HVAC vents masked during demo, unmasked after final cleanup",
            ],
        },
        {
            "category": "Installation Craft",
            "icon": "🔨",
            "points": [
                "Start-line and reference-line snapped from longest visible sightline",
                "Expansion gaps maintained per manufacturer spec (typically 1/2″ at every wall)",
                "Plank stagger minimum 6″–8″ end-to-end across rows — no H-pattern or stair-step",
                "Hardwood blind-nailed at proper angle and depth, never face-nailed except at perimeter",
                "Glue-down adhesive trowel notch sized to manufacturer spec for that plank thickness",
                "Tile lippage controlled with leveling clip systems on every install above 12″ format",
                "Mortar consistency tested by hand on every batch — no slumping, no over-watering",
                "Grout joints sized to manufacturer spec, never narrower for visual preference",
                "Transition strips fitted, fastened, and finished in matching trim line",
                "Quarter-round and shoe-mold mitered and color-matched to baseboard or floor",
            ],
        },
        {
            "category": "Quality Control & Walk-Through",
            "icon": "✅",
            "points": [
                "End-of-day cleanup every day of the install — never leave job dirty",
                "Final clean and detail before homeowner walk-through",
                "Walk every plank, every tile, every transition with homeowner present",
                "Punch list signed before final invoice — anything not right gets fixed before payment",
                "Acclimation log, moisture readings, and material lot numbers handed over in writing",
                "Care-and-maintenance guide left with homeowner for the installed product",
                "Two-year written workmanship warranty signed and dated",
                "Manufacturer warranty paperwork organized, dated, and filed",
                "Photo documentation of finished install added to job folder",
                "Follow-up call at 30 days, 6 months, and 12 months — by the owner, not a CSR",
                "Free annual inspection in year one — preventive catch on anything moving wrong",
                "Direct line to the owner for the full warranty period, no call-center hand-off",
            ],
        },
    ],
}

# ============================================================================
# REVIEWS — 12 placeholder reviews. Replace with real Google Reviews
# as Luciano collects them. Format: (name, city, service, rating, date, text)
# ============================================================================
REVIEWS = [
    ("Jennifer M.","Lakewood Ranch","Engineered hardwood","5.0","2026-03",
     "Hired Sarasota Flooring Company to install 1,400 sq ft of wide-plank European white oak in our Country Club East home. The owner was on-site every single day. Acclimation log, moisture readings, batch numbers — all documented and handed to us at the end. The floor is gorgeous and the experience was the best contractor experience we've had in five years of owning this house."),
    ("Robert K.","Siesta Key","LVP for short-term rental","5.0","2026-03",
     "We needed to reflooring our Siesta Key beach rental between bookings. Got the call out Wednesday, materials on-site Friday, install finished Sunday night — three days, no shortcuts. The wider-plank SPC he recommended is gorgeous in the listing photos and has already taken a season of turnover without a scratch."),
    ("Maria S.","Sarasota","Bathroom tile + Kerdi shower","5.0","2026-02",
     "Found Sarasota Flooring Company after two failed quotes from bigger contractors who wanted to skip the Schluter waterproofing. He insisted on doing the shower right, walked me through the TCNA spec, and the finished bathroom is exactly what I'd hoped for. Two years written warranty in writing — that's the kind of accountability I was looking for."),
    ("David & Lynn P.","Bradenton","Engineered hardwood + tile","5.0","2026-02",
     "Whole-house renovation in River Strand — engineered hardwood in the living areas, large-format tile in the bathrooms. Three weeks total work, on schedule every day. The 63-point checklist isn't just marketing — they actually went through every item. Floors look incredible six months in."),
    ("Thomas H.","Venice","Solid hardwood restoration","5.0","2026-02",
     "Original 1958 oak floors in our Island of Venice cottage. Other installers wanted to rip and replace. Sarasota Flooring Co. assessed, sanded down 1/16″, refinished in three coats of water-based finish, and gave me back the original floor — only better than I remembered it. The right answer is sometimes 'don't replace it.' Appreciated the honesty."),
    ("Patricia W.","Longboat Key","Large-format porcelain (3rd-floor condo)","5.0","2026-01",
     "Mid-rise condo install on the 3rd floor of L'Ambiance. Freight-elevator scheduling, HOA approval packet, neighbor notification — everything handled. The 24x48 porcelain in the great room is perfectly flat, no lippage, no telegraphing of the slab below. Worth every dollar."),
    ("Michael R.","Parrish","LVP throughout (new construction)","5.0","2026-01",
     "Closed on our North River Ranch home and immediately wanted to ditch the builder carpet in the bedrooms. Sarasota Flooring Co. did the whole upstairs in mid-range SPC in two days. Owner was here both days. Best contractor experience we've had since moving to Florida from Ohio."),
    ("Elizabeth T.","Palmetto","Stair tread replacement","5.0","2026-01",
     "Replaced the carpeted stairs in our Riviera Dunes townhome with engineered oak treads matched to the field floor. Two days, no mess, no surprise costs. The staircase reads as part of the same install as the downstairs — exactly what I wanted."),
    ("Sandra L.","Lakewood Ranch","Tile + LVP combo","5.0","2025-12",
     "Esplanade Golf install — tile in the wet areas, LVP everywhere else, all transitions flush-mounted so the floor reads as one continuous surface. The transitions alone tell you this is craft work, not commodity install. We've had three neighbors ask for the referral."),
    ("Frank D.","Sarasota","Floor repair (water damage)","5.0","2025-12",
     "Dishwasher flooded our kitchen overnight; lost about 80 sq ft of engineered hardwood. Called Sarasota Flooring Co. expecting a hard sell on a full replacement. Got the opposite — they sourced a matching batch, replaced 87 planks, and the repair is invisible. Saved us a full reflooring. Fair, honest, fast."),
    ("Karen B.","Bradenton","Laminate (high-traffic home office)","5.0","2025-11",
     "AC5 commercial-grade laminate in my home office — runs from the front door through the office and into the conference room. Eight months and ~300 client visits in, and it looks brand new. The owner talked me out of LVP on this room and into laminate for the scratch resistance. Right call."),
    ("Steven J.","Venice","Floor repair (cracked tile)","5.0","2025-11",
     "Three cracked tiles in our entryway from a heavy piece of furniture dropped during a move. Pulled the three damaged tiles, grout-matched the replacement, and you cannot tell which tiles are the originals. $300 fix instead of a $3,000 tile rip-out. Honest pricing, fast execution."),
]

# ============================================================================
# HOMEPAGE COMPONENTS
# ============================================================================
HERO_TRUST_BADGES = [
    "Owner on every job",
    "TCNA-spec installations",
    "2-year written warranty",
    "Free estimate in 24 hours",
]

WHY_US_POINTS = [
    {
        "icon": "👷",
        "title": "The owner is on every install.",
        "body": "No subcontracted crews. Every job is hand-supervised from start to walk-through. The number on this site is the owner's direct line — call it any day of the install, including after the warranty kicks in.",
    },
    {
        "icon": "📋",
        "title": "63-point installation standard, documented.",
        "body": "Acclimation logs, moisture readings, batch and lot numbers, photo documentation. Every job folder lands in your hands at walk-through. You'll know exactly what was installed, how, and where to source matching material in the future.",
    },
    {
        "icon": "🛡️",
        "title": "Two-year written workmanship warranty.",
        "body": "The longest workmanship warranty in the Sarasota–Manatee market. Anything that moves wrong inside two years — gapping, cupping, lippage, seam separation — gets corrected at no charge. In writing, signed and dated.",
    },
    {
        "icon": "🏝️",
        "title": "We know the barrier-island climate.",
        "body": "Salt-air corrosion. Hurricane-recovery moisture cycles. Mid-rise condo HOA logistics. Acclimation gradients between conditioned interiors and unconditioned garages. Five years of installing in Siesta, Longboat, and Anna Maria sharpens those calls.",
    },
    {
        "icon": "💰",
        "title": "Pricing on the table — no shell-game quotes.",
        "body": "Every quote itemized: material, labor, subfloor prep, demo, haul-away, transitions. No 'allowance' line items hiding upcharges. The number we sign is the number you pay, unless something genuinely changes mid-project that we walk you through before it changes the bill.",
    },
    {
        "icon": "⏱️",
        "title": "24-hour estimate response — often same day.",
        "body": "Call or text the owner directly. Most weeks we can be at your house with samples and a tape measure inside twenty-four hours. Estimates are free, sample bring-outs are free, and we don't sell you on the spot — you get the quote in writing and decide on your time.",
    },
]

PROCESS_STEPS = [
    ("01","Free In-Home Estimate",
     "Call or text and we'll be at your home — often same day — with material samples sized for your lighting, your finishes, and your furniture. Free, no obligation, no pressure."),
    ("02","Written Quote &amp; Material Selection",
     "Itemized written estimate within 24 hours. Material, labor, subfloor prep, demo, haul-away — every line listed. We help you pick the product, you decide on your timeline."),
    ("03","Installation by the Owner",
     "We schedule the install around your life. The owner is on-site every day of the job, working the floor and supervising the work. End-of-day cleanups every day, including the last."),
    ("04","Walk-Through &amp; 2-Year Warranty",
     "Sign-off walkthrough with the owner, plank by plank, before the final invoice. Two-year written workmanship warranty handed over in writing. Direct-line follow-up at 30 days, 6 months, and 1 year."),
]

# ============================================================================
# BLOG POST TOPICS
# General editorial pieces (3) + cost-by-city posts (6 services × 8 cities = 48)
# ============================================================================
GENERAL_BLOG_POSTS = [
    {
        "slug": "best-flooring-sarasota-humidity",
        "title": "The Best Flooring for Sarasota's Humidity (2026 Guide)",
        "h1": "The Best Flooring for Sarasota's Humidity — A 2026 Guide for Homeowners",
        "summary": "Sarasota's coastal humidity is the deciding factor in nearly every flooring choice. Here's what works, what doesn't, and why — broken down by room and by climate zone.",
        "category": "Buyer's Guide",
        "read_time": "12 min read",
        "date": "2026-04-15",
    },
    {
        "slug": "flooring-short-term-rental-sarasota",
        "title": "Flooring for Short-Term Rentals in Sarasota & Siesta Key",
        "h1": "The Right Flooring for Short-Term Rentals in Sarasota, Siesta Key & Longboat",
        "summary": "STR floors take five times the wear of a primary residence and need to look new in listing photos for a decade. After 140+ STR reflooring jobs, here's our spec.",
        "category": "Investor Guide",
        "read_time": "10 min read",
        "date": "2026-03-22",
    },
    {
        "slug": "lakewood-ranch-flooring-replacement-window",
        "title": "When Lakewood Ranch Builder Floors Hit Their Replacement Window",
        "h1": "When Lakewood Ranch Builder Floors Hit Their Replacement Window — and What to Replace Them With",
        "summary": "The vast majority of Lakewood Ranch homes were built between 2005 and 2015 with builder-grade engineered hardwood or porcelain tile. Both products are hitting their 15-to-20-year replacement window now. Here's the scope, the budget, and the smart upgrade paths.",
        "category": "Community Guide",
        "read_time": "11 min read",
        "date": "2026-02-10",
    },
]

# Cost-by-city posts: pre-generated topic shells, content is templated by build script
COST_BLOG_POSTS = []  # populated by _build_blog.py from SERVICES × CITIES matrix
